remote_theme: supun-io/jekyll-theme-leaf
plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-feed
baseurl: ""
url: "https://alyceosbourne.github.io"
theme_mode: dark
title: [CthuluCodesGames]
iconURL: cthulu.png
social:
  github: AlyceOsbourne
