remote_theme: supun-io/jekyll-theme-leaf
plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
theme_mode: dark
title: [CthuluCodesGames]
iconURL: cthulu.png
url: AlyceOsbourne.github.io
baseUrl: /godot_blog
social:
  github: AlyceOsbourne
