remote_theme: supun-io/jekyll-theme-leaf
plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-feed
url: https://alyceosbourne.github.io/godot_blog/
theme_mode: dark
title: [CthuluCodesGames]
iconURL: cthulu.png
social:
  github: AlyceOsbourne
